### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by rigwild** [Nooaah/API-REST-Node#1]
Hello,

Database queries are vulnerable to SQL injection.

https://github.com/Nooaah/API-REST-Node/blob/27b004608e0e4ce2184f1555a8497e5df98f91ac/index.js#L31

You should not inject parameters in a string (even with template litterals). The user could send a malicious request.

User's arguments should be sent to the `mysql` library, which properly escape it.

See [Preparing Queries](https://www.npmjs.com/package/mysql#preparing-queries)

Have a nice day!

**Comment by Nooaah** [comment]
Salut,
Justement j'y ai pensé tout à l'heure quand j'ai testé d'insérer des éléments dans une bdd avec mon bot discord
Merci du conseil !
